project:
  type: book
  output-dir: docs

toc: true
number-sections: true
toc-depth: 2
number-depth: 4
bibliography: book.bib
csl: C:/Users/Xinli/Documents/ims.csl

format:
  html:
    theme: [cosmo, theme.scss]
    page-layout: article
    # include-before-body: contents/math.qmd
crossref:
  appendix-title: "Appendix "
  appendix-delim: ":"
book:
  title: "Bayesian"
  subtitle: "Notes"
  description: "Homepage Spring 2023."
  author: "Xinli Xiao"
  date: last-modified
  chapters: 
    - index.qmd
    - part: contents/0/rv.qmd
      chapters:
          - contents/0/prob.qmd 
          - contents/0/inferences.qmd
          - contents/0/rv1.qmd
    - part: contents/1/notations.qmd
      chapters: 
        - contents/1/dist/binom.qmd
    #     - contents/1/dist/beta.qmd
    #     - contents/1/dist/geo.qmd
        - contents/1/dist/poisson.qmd
        - contents/1/dist/gamma.qmd
    #     - contents/1/dist/exp.qmd
    #     - contents/1/dist/normal.qmd
    - part: contents/2/bayes.qmd
      chapters:
        - contents/2/bayesthm.qmd
    - contents/references.qmd
  appendices:
    - contents/app/specialfunctions.qmd
  sidebar:
    # background: "#D9E3E4"
    border: true
    search: true
    collapse-level: 1
    pinned: true
    # style: docked
    align: center
    tools:
      - icon: github
        text: Source Code
        href: https://github.com/xiaoxl/bayesian
  # navbar:
  #   subtitle: "2022 Fall"
  #   pinned: false
  page-navigation: true







